name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ReturnToMoriaServerManager.sln
      
    - name: Build
      run: dotnet build ReturnToMoriaServerManager.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ReturnToMoriaServerManager.sln --configuration Release --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish ReturnToMoriaServerManager/ReturnToMoriaServerManager.csproj --configuration Release --output ./publish --self-contained false
      
    - name: Create Package
      run: |
        $version = "latest"
        $packageName = "ReturnToMoriaServerManager-$version.zip"
        
        New-Item -ItemType Directory -Path "./package" -Force
        Copy-Item -Path "./publish/*" -Destination "./package/" -Recurse
        Copy-Item -Path "./README.md" -Destination "./package/"
        Copy-Item -Path "./LICENSE" -Destination "./package/"
        
        Compress-Archive -Path "./package/*" -DestinationPath "./$packageName" -Force
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ReturnToMoriaServerManager
        path: ReturnToMoriaServerManager-latest.zip
        retention-days: 30 