name: Generate Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.cs'
      - '**.xaml'
      - 'README.md'
      - 'CONTRIBUTING.md'
  pull_request:
    branches: [ main, develop ]

jobs:
  docs:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Install DocFX
      run: |
        dotnet tool install -g docfx
        docfx --version
        
    - name: Generate Documentation
      run: |
        docfx init -q
        docfx docfx.json
        
    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: Documentation
        path: ./_site/
        retention-days: 30 