name: Generate Status Badges

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  generate-badges:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Generate Badges
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: your-gist-id
        filename: return-to-moria-server-manager.json
        label: build
        message: passing
        color: green
        namedLogo: github 