name: Update Dependencies

on:
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2 AM
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Check for outdated packages
      run: |
        dotnet list package --outdated --format json > outdated-packages.json
        
    - name: Update packages
      run: |
        dotnet outdated --upgrade
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(deps): update dependencies'
        title: 'chore(deps): update dependencies'
        body: |
          ## Dependency Updates
          
          This PR updates the project dependencies to their latest versions.
          
          ### Changes
          - Updated NuGet packages to latest versions
          - Improved security and performance
          
          ### Testing
          - [ ] Build passes
          - [ ] Tests pass
          - [ ] Application runs correctly
          
          ### Notes
          Please review the changes and test thoroughly before merging.
        branch: update-dependencies
        delete-branch: true 